##
## Build
##
FROM node:lts-alpine as build-stage

ARG VERSION=v1.0.0
ARG API_URL=/api

WORKDIR /app

RUN echo "VITE_API_URL=${API_URL}\nVITE_VERSION=${VERSION}" > .env

COPY front/ ./

RUN npm install
RUN npm run build

##
## Deploy
##
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

